const actionTypes = {
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  RECEIVE_USER_DATA: 'RECEIVE_USER_DATA',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  FETCH_LISTINGS: 'FETCH_LISTINGS',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
  RECEIVE_LISTINGS: 'RECEIVE_LISTINGS',
  UPDATE_LISTINGS: 'UPDATE_LISTINGS',
  STORE_LISTING: 'STORE_LISTING',
  LOAD_SAVED_LISTINGS: 'LOAD_SAVED_LISTINGS',
  LOAD_SAVED_SEARCHES: 'LOAD_SAVED_SEARCHES',
  LOAD_SAVED_COLLECTIONS: 'LOAD_SAVED_COLLECTIONS',
  UPDATE_COLLECTION: 'UPDATE_COLLECTION',

  INITIALIZE_APP: 'INITIALIZE_APP',
  GET_GEOLOCATION: 'GET_GEOLOCATION',
  RECEIVE_GEOLOCATION: 'RECEIVE_GEOLOCATION'
}

export default actionTypes;