'use strict';

const actionTypes = {
  INITIALIZE_APP: 'INITIALIZE_APP',
  GET_GEOLOCATION: 'GET_GEOLOCATION',
  RECEIVE_GEOLOCATION: 'RECEIVE_GEOLOCATION',

  RECEIVE_USER_DATA: 'RECEIVE_USER_DATA',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  SUBMIT_SEARCH: 'SUBMIT_SEARCH',
  RECEIVE_SEARCH_RESULTS: 'RECEIVE_SEARCH_RESULTS',
  CANCEL_REQUEST: 'CANCEL_REQUEST',

  LOAD_HOME_DATA: 'LOAD_HOME_DATA',
  LOAD_FAVORITES: 'LOAD_FAVORITES',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',

  SAVE_TO_STORAGE: 'SAVE_TO_STORAGE',
  REMOVE_FROM_STORAGE: 'REMOVE_FROM_STORAGE',
  LOAD_LISTINGS_FROM_STORAGE: 'LOAD_LISTINGS_FROM_STORAGE',
  CLEAR_ALL_FROM_STORAGE: 'CLEAR_ALL_FROM_STORAGE'
}

export default actionTypes;